//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetShelter.Model
{
    using System;
    using System.Collections.Generic;
    using System.Reflection;
    
    public partial class Animal : DbEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Animal()
        {
            this.Contracts = new HashSet<Contract>();
            this.StateValues = new HashSet<StateValue>();
            this.Vaccinations = new HashSet<Vaccination>();
        }
    
        public int AnimalID { get; set; }
        public string Name { get; set; }
        public string Sex { get; set; }
        public string AnimalKind { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<double> Weight { get; set; }
        public string Color { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public Nullable<int> QuarantineDays { get; set; }
        public Nullable<int> RoomID { get; set; }
        public Nullable<int> GroupID { get; set; }
    
        internal virtual Group Group { get; set; }
        internal virtual Room Room { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        internal virtual ICollection<Contract> Contracts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        internal virtual ICollection<StateValue> StateValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        internal virtual ICollection<Vaccination> Vaccinations { get; set; }

        public override List<DbEntity> GetForegnEntities()
        {
            var res = new List<DbEntity>();

            foreach (StateValue val in StateValues)
            {
                res.Add(val);
            }

            return res;
        }

        public override Dictionary<string, string> GetProperies()
        {
            var res = new Dictionary<string, string>();

            foreach (PropertyInfo prop in GetType().GetProperties())
            {
                res.Add(prop.Name, (prop.GetValue(this) ?? "-").ToString());
            }

            return res;
        }

        public override string ToString()
        {
            return "Animal";
        }
    }
}
