//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetShelter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Caretaker
    {
        public int PassNum { get; set; }
        public string Shift { get; set; }
        public string MajorAnimalKind { get; set; }
        public string MedicalEducation { get; set; }
        public Nullable<int> RoomID { get; set; }
    
        public virtual Emploee Emploee { get; set; }
        public virtual Room Room { get; set; }
    }
}
