//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetShelter.Model
{
    using System;
    using System.Collections.Generic;
    using System.Reflection;
    
    public partial class Contract : DbEntity
    {
        public int ContractNum { get; set; }
        public Nullable<int> PassNum { get; set; }
        public Nullable<int> AnimalID { get; set; }
        public Nullable<System.DateTime> SigningDate { get; set; }
        public Nullable<System.DateTime> TerminationDate { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> IDCardNum { get; set; }
    
        internal virtual Animal Animal { get; set; }
        internal virtual Client Client { get; set; }
        internal virtual InfoDepEmploee InfoDepEmploee { get; set; }

        public override Dictionary<string, string> GetProperies()
        {
            var res = new Dictionary<string, string>();

            foreach (PropertyInfo prop in GetType().GetProperties())
            {
                res.Add(prop.Name, (prop.GetValue(this) ?? "-").ToString());
            }

            return res;
        }
    }
}
