//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetShelter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contracts
    {
        public int ContractNum { get; set; }
        public Nullable<int> PassNum { get; set; }
        public Nullable<int> AnimalID { get; set; }
        public Nullable<System.DateTime> SigningDate { get; set; }
        public Nullable<System.DateTime> TerminationDate { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> IDCardNum { get; set; }
    
        public virtual Animals Animals { get; set; }
        public virtual Clients Clients { get; set; }
        public virtual InfoDepEmploees InfoDepEmploees { get; set; }
    }
}
