//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetShelter.Model
{
    using System;
    using System.Collections.Generic;
    using System.Reflection;

    public partial class Group : DbEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Group()
        {
            this.Animals = new HashSet<Animal>();
        }

        private int groupID;
        private int priority;
        private string readiness;
        private string additionalCare;
        private string description;

        public int GroupID
        {
            get { return groupID; }
            set
            {
                groupID = value;
                OnPropertyChanged("GroupID");
            }
        }
        public int Priority
        {
            get { return priority; }
            set
            {
                priority = value;
                OnPropertyChanged("Priority");
            }
        }
        public string Readiness
        {
            get { return readiness; }
            set
            {
                readiness = value;
                OnPropertyChanged("Readiness");
            }
        }
        public string AdditionalCare
        {
            get { return additionalCare; }
            set
            {
                additionalCare = value;
                OnPropertyChanged("AdditionalCare");
            }
        }
        public string Description
        {
            get { return description; }
            set
            {
                description = value;
                OnPropertyChanged("Description");
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        internal virtual ICollection<Animal> Animals { get; set; }

        public override Dictionary<string, string> GetProperies()
        {
            var res = new Dictionary<string, string>();

            foreach (PropertyInfo prop in GetType().GetProperties())
            {
                res.Add(prop.Name, (prop.GetValue(this) ?? "-").ToString());
            }

            return res;
        }

        public override List<DbEntity> GetForegnEntities()
        {
            var res = new List<DbEntity>();

            foreach (Animal animal in Animals)
            {
                res.Add(animal);
            }

            return res;
        }

        public override string ToString()
        {
            return "Група";
        }

        public override string GetSearchString()
        {
            return $"{GroupID} {Description} {AdditionalCare}";
        }
    }
}
