//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetShelter.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataContext : DbContext
    {
        public DataContext()
            : base("name=PetShelterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Animal>()
               .HasMany(a => a.StateValues)
               .WithOptional(s => s.Animal)
               .HasForeignKey(s => s.AnimalID);

            modelBuilder.Entity<StateValue>()
                .HasOptional(s => s.State)
                .WithMany(s => s.StateValues)
                .HasForeignKey(s => s.StateID);
        }
    
        public virtual DbSet<Animal> Animals { get; set; }
        public virtual DbSet<Caretaker> Caretakers { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Contract> Contracts { get; set; }
        public virtual DbSet<Emploee> Emploees { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<InfoDepEmploee> InfoDepEmploees { get; set; }
        public virtual DbSet<Producer> Producers { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<StateValue> StateValues { get; set; }
        public virtual DbSet<Vaccination> Vaccinations { get; set; }
        public virtual DbSet<Vaccine> Vaccines { get; set; }
    }
}
