//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetShelter.Model 
{
    using System;
    using System.Collections.Generic;
    using System.Reflection;
    
    public partial class StateValue : DbEntity
    {
        private int stateValueID;
        private Nullable<int> stateID;
        private Nullable<int> animalID;
        private string value;


        public int StateValueID
        {
            get { return stateValueID; }
            set
            {
                stateValueID = value;
                OnPropertyChanged("StateValueID");
            }
        }
        public Nullable<int> StateID 
        {
            get { return stateID; }
            set
            {
                stateID = value;
                OnPropertyChanged("StateID ");
            }
        }
        public Nullable<int> AnimalID 
        {
            get { return animalID; }
            set
            {
                animalID = value;
                OnPropertyChanged("AnimalID");
            }
        }
        public string Value 
        {
            get { return value; }
            set
            {
                this.value = value;
                OnPropertyChanged("Value");
            }
        }
    
        internal virtual Animal Animal { get; set; }
        internal virtual State State { get; set; }

        public override List<DbEntity> GetForegnEntities()
        {
            return null;
        }

        public override Dictionary<string, string> GetProperies()
        {
            var res = new Dictionary<string, string>();

            foreach (PropertyInfo prop in GetType().GetProperties())
            {
                res.Add(prop.Name, (prop.GetValue(this) ?? "-").ToString());
            }

            return res;
        }

        public override string ToString()
        {
            string value = State.Name;
            value.Trim();

            if (value.EndsWith("стан"))
            {
                return value + " тварини";
            }
            else
            {
                return value;
            }
        }
    }
}
