//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetShelter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StateValues
    {
        private int stateValueID;
        private Nullable<int> stateID;
        private Nullable<int> animalID;
        private string value;

        public int StateValueID { get; set; }
        public Nullable<int> StateID { get; set; }
        public Nullable<int> AnimalID { get; set; }
        public string Value { get; set; }
    
        public virtual Animals Animals { get; set; }
        public virtual States States { get; set; }
    }
}
