//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetShelter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vaccines
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vaccines()
        {
            this.Vaccinations = new HashSet<Vaccinations>();
        }
    
        public int VaccineID { get; set; }
        public string VaccineName { get; set; }
        public string ActiveSubstanceName { get; set; }
        public string ActiveSubstanceLatinName { get; set; }
        public Nullable<int> RevaccinationDogs { get; set; }
        public Nullable<int> RevaccinationRodents { get; set; }
        public Nullable<int> RevaccinationMeatEaters { get; set; }
        public Nullable<int> ProducerID { get; set; }
    
        public virtual Producers Producers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vaccinations> Vaccinations { get; set; }
    }
}
